print("Hello! Welcome to a game of Pig!")
print("           9")
print("     ,--.-'-,--.")
print("     \\  /-~-\\  /")
print("    / )' a a `( \\")
print("   ( (  ,---.  ) )")
print("    \\ `(_o_o_)' /")
print("     \\   `-'   /")
print("      | |---| |  ")
print("      [_]   [_]")
